### ISSUE TITLE
Calling block from another block raised

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#54]
```ruby
def f(x, &block)
  l = ->(y : Int) { block.call(y) }
  l.call(x)
end

f(1) { |x| p x }
```

```
/home/kostya/crystal/lib/crystal/codegen/llvm_typer.rb:47:in `llvm_type': Unexepcted type  in llvm_type (RuntimeError)
	from /home/kostya/crystal/lib/crystal/codegen.rb:115:in `llvm_type'
	from /home/kostya/crystal/lib/crystal/codegen.rb:1400:in `codegen_fun'
	from /home/kostya/crystal/lib/crystal/codegen.rb:220:in `visit_fun_literal'
	from /home/kostya/crystal/lib/crystal/ast.rb:31:in `accept'
	from /home/kostya/crystal/lib/crystal/codegen.rb:160:in `accept'
	from /home/kostya/crystal/lib/crystal/codegen.rb:390:in `codegen_assign_node'
	from /home/kostya/crystal/lib/crystal/codegen.rb:371:in `visit_assign'
	from /home/kostya/crystal/lib/crystal/ast.rb:31:in `accept'
	from /home/kostya/crystal/lib/crystal/codegen.rb:160:in `accept'
	from /home/kostya/crystal/lib/crystal/codegen.rb:291:in `block in visit_expressions'
	from /home/kostya/crystal/lib/crystal/codegen.rb:290:in `each'
	from /home/kostya/crystal/lib/crystal/codegen.rb:290:in `visit_expressions'
	from /home/kostya/crystal/lib/crystal/ast.rb:31:in `accept'
	from /home/kostya/crystal/lib/crystal/codegen.rb:160:in `accept'
	from /home/kostya/crystal/lib/crystal/codegen.rb:1073:in `visit_call'
	from /home/kostya/crystal/lib/crystal/ast.rb:31:in `accept'
	from /home/kostya/crystal/lib/crystal/codegen.rb:160:in `accept'
	from /home/kostya/crystal/lib/crystal/codegen.rb:291:in `block in visit_expressions'
	from /home/kostya/crystal/lib/crystal/codegen.rb:290:in `each'
	from /home/kostya/crystal/lib/crystal/codegen.rb:290:in `visit_expressions'
	from /home/kostya/crystal/lib/crystal/ast.rb:31:in `accept'
	from /home/kostya/crystal/lib/crystal/codegen.rb:32:in `build'
	from /home/kostya/crystal/lib/crystal/compiler.rb:149:in `block in compile_with_stats_and_profile'
	from /home/kostya/crystal/lib/crystal/compiler.rb:204:in `call'
	from /home/kostya/crystal/lib/crystal/compiler.rb:204:in `with_stats_or_profile'
	from /home/kostya/crystal/lib/crystal/compiler.rb:148:in `compile_with_stats_and_profile'
	from /home/kostya/crystal/lib/crystal/compiler.rb:110:in `compile'
	from ./bin/crystal:10:in `<main>'

```

**Comment by yui-knk** [comment]
On 0.7.5 these codes work!

```crystal
def f(x, &block : Int32 -> Int32)
  l = ->(y : Int32) { block.call(y) }
  l.call(x)
end

f(1) { |x| p x }
# 1
```

```crystal
def f(&block)
  yield 1
end

def g(&block : Int32 -> Int32)
  f(&block)
end

g { |x| p x }
# 1
```

* type of `&block` is need
* `Int` is not valid, `Int32` is valid

Can we close this issue?

**Comment by asterite** [comment]
@yui-knk I think that now that the semantics of the language are more defined, we can close this issue. @kostya what do you think?
